Disable SSL certificate for tests
ably/ably-php pull request #136
Opened 2022-03-17 11:28 UTC by sacOO7

- Disabled SSL certificate while sending a request to Ably Sandbox.
- Fixed error `[SSL certificate error: unable to get local issuer certificate]`

2022-03-17 15:25 UTC, owenpearson reviewed
Code looks fine but I'm not sure I'm comfortable with us making this change. The TestApp API should have a valid certificate so if there's a problem with validating it then we should try and understand exactly what that problem is. I see that we got an SSL error in CI [here](https://github.com/ably/ably-php/actions/runs/1933625355/attempts/1) but the issue didn't occur again when I re-ran the tests so I'd guess that was a temporary issue with GitHub runners. If you're consistently seeing the same error locally then I'd guess there's an issue with your local openssl installation?

2022-03-18 00:01 UTC, sacOO7 commented
> Code looks fine but I'm not sure I'm comfortable with us making this change. The TestApp API should have a valid certificate so if there's a problem with validating it then we should try and understand exactly what that problem is. I see that we got an SSL error in CI [here](https://github.com/ably/ably-php/actions/runs/1933625355/attempts/1) but the issue didn't occur again when I re-ran the tests so I'd guess that was a temporary issue with GitHub runners. If you're consistently seeing the same error locally then I'd guess there's an issue with your local openssl installation?

The error says `[SSL certificate error: unable to get local issuer certificate]`. So, the issue is surely from the local certificate.  I am currently using the `windows` machine. I have done a fresh installation of PHP. I am using PHP `8.1.4`. Since we are using `test` env. anyways, I don't think it is a big issue disabling the SSL verification (We are still verifying the correct host). I think we need to confirm this issue doesn't occur on github again. It can, depending on the machine available at the time of test run.

2022-03-18 20:23 UTC, lmars commented
The Ably sandbox cluster uses a public TLS certificate issued by AWS, and it uses the same issuance system as our production TLS certificates.

If you're getting TLS related errors, we should investigate the root cause and fix the underlying issue rather than disabling verification, as this may well affect other clients connecting to production.

2022-03-22 07:56 UTC, sacOO7 commented
@lmars it seems we have multiple `tests` using the internal `HTTP` class. Since we can't disable SSL for a non-test environment, I will only keep the code that reports errors with the server. I will also update the doc on how to resolve the error for windows environments.

2022-03-22 10:57 UTC, lmars commented
@sacOO7 so do you know what the root cause of the verification issue is?

2022-03-22 11:31 UTC, QuintinWillison requested changes
I think it's clear that this is not the right way to fix this issue. It should be within scope / acceptance criteria of tests running against the sandbox environment that they properly negotiate their secure connections to the Ably service.

2022-03-22 11:51 UTC, sacOO7 commented
> @sacOO7 so do you know what the root cause of the verification issue is?

Yeah, adding downloading and updating `SSL` certificate as per https://aboutssl.org/fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate/ fixed my issue. I think issue might be common for windows machines since the entry for the local SSL certificate was empty in `php.ini`.

2022-03-22 12:04 UTC, QuintinWillison commented
Interesting. I notice we only run integration tests in CI on Ubuntu runners at the moment. Perhaps we should add Windows to that mix.

2022-03-28 15:02 UTC, owenpearson approved these changes
LGTM, thanks, just one minor suggestion

2022-03-28 15:56 UTC, sacOO7 commented on README.md
> +Currently, this SDK only supports [Ably REST](https://www.ably.io/documentation/rest). However, you can use the [MQTT adapter](https://www.ably.io/documentation/mqtt) to implement [Ably's Realtime](h
Actually, it's officially recommended here https://ably.com/download. You can see the section `MQTT`

2022-03-28 19:34 UTC, owenpearson commented on README.md
> +Currently, this SDK only supports [Ably REST](https://www.ably.io/documentation/rest). However, you can use the [MQTT adapter](https://www.ably.io/documentation/mqtt) to implement [Ably's Realtime](h
OK, that's fair enough then. We should still change the link text to say 'Mosquitto PHP' rather than just 'PHP' though.

2022-03-29 10:21 UTC, sacOO7 commented on README.md
> +Currently, this SDK only supports [Ably REST](https://www.ably.io/documentation/rest). However, you can use the [MQTT adapter](https://www.ably.io/documentation/mqtt) to implement [Ably's Realtime](h
Done

2022-03-30 15:13 UTC, merged