Update readme, laravel section
ably/ably-php pull request #170
Opened 2022-10-30 14:09 UTC by sacOO7

- Updated laravel section with `laravel-broadcaster`
- Updated release process
- Fixes #169

2022-10-31 11:13 UTC, owenpearson requested changes

2022-10-31 11:49 UTC, sacOO7 commented on README.md
> +>If you want **ably-php** as a rest dependency across service providers, check [ably-php-laravel](https://packagist.org/packages/ably/ably-php-laravel). **ably-php-laravel** is a simple wrapper over
updated!

2022-10-31 11:49 UTC, sacOO7 commented on README.md
> +## Laravel realtime broadcasting is now officially supported!
updated!

2022-10-31 20:14 UTC, qsdstefan commented on README.md
> +> If you want **ably-php** as a rest dependency across service providers, check [ably-php-laravel](https://packagist.org/packages/ably/ably-php-laravel). **ably-php-laravel** is a simple wrapper over
brodcaster -> broadcaster

2022-10-31 20:15 UTC, qsdstefan requested changes
Please fix the typo and I'll happily approve

2022-11-01 04:46 UTC, sacOO7 commented on README.md
> +> If you want **ably-php** as a rest dependency across service providers, check [ably-php-laravel](https://packagist.org/packages/ably/ably-php-laravel). **ably-php-laravel** is a simple wrapper over
updated!

2022-11-02 14:11 UTC, owenpearson approved these changes
LGTM

2022-11-07 15:24 UTC, qsdstefan approved these changes
LGTM!

2022-11-07 16:02 UTC, AmirQSD approved these changes
LGTM

2022-11-08 18:09 UTC, merged